"use client";
import {useEffect,useState} from "react";
import {getSupabase} from "../lib/supabase";
const stats=[["Revenue","revenue"],["Expenses","expenses"],["Profit","profit"],["Customers","customers"]];
export default function Home(){
 const [data,setData]=useState({revenue:0,expenses:0,profit:0,customers:0}),[business,setBusiness]=useState(null),[message,setMessage]=useState("");
 const supabase=getSupabase();
 useEffect(()=>{load()},[]);
 async function load(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:b}=await supabase.from("businesses").select("*").eq("owner_id",user.id).order("created_at",{ascending:true}).limit(1).maybeSingle();setBusiness(b);if(!b)return;const[{data:s},{data:e},{count}]=await Promise.all([supabase.from("sales").select("amount").eq("business_id",b.id),supabase.from("expenses").select("amount").eq("business_id",b.id),supabase.from("customers").select("*",{count:"exact",head:true}).eq("business_id",b.id)]);const revenue=(s||[]).reduce((a,x)=>a+Number(x.amount||0),0),costs=(e||[]).reduce((a,x)=>a+Number(x.amount||0),0);setData({revenue,expenses:costs,profit:revenue-costs,customers:count||0})}
 const money=n=>"R "+n.toLocaleString("en-ZA",{minimumFractionDigits:2,maximumFractionDigits:2});
 return <main className="shell"><aside className="sidebar"><div className="brand"><div className="logo">R</div><div><strong>Business OS</strong><span>by Rapsometeddy</span></div></div><nav>{["Dashboard","Customers","Products","Sales","Expenses","Invoices","Reports"].map((x,i)=><button className={i===0?"nav active":"nav"} key={x}><span>{["⌂","♙","▦","↗","↘","▤","▥"][i]}</span>{x}</button>)}</nav><div className="sidebarBottom"><div className="miniCard"><span className="eyebrow">LIVE DATA</span><strong>{business?.name||"No business yet"}</strong><small>Supabase connected</small></div></div></aside><section className="content"><header className="topbar"><div><span className="eyebrow">OVERVIEW</span><h1>{business?.name||"Business OS"} 👋</h1><p>Your business at a glance.</p></div><button className="primary" onClick={()=>location.href="/setup"}>Set up business</button></header><section className="stats">{stats.map(([label,key])=><article className="stat" key={key}><span>{label}</span><strong>{key==="customers"?data[key]:money(data[key])}</strong><small>Live from Supabase</small></article>)}</section><section className="grid"><article className="panel chart"><div className="panelHead"><div><span className="eyebrow">PERFORMANCE</span><h2>Revenue overview</h2></div><span className="pill">Live</span></div><div className="emptyChart"><p>Live revenue: {money(data.revenue)}</p><p>Profit: {money(data.profit)}</p></div></article><article className="panel"><div className="panelHead"><div><span className="eyebrow">QUICK START</span><h2>Take action</h2></div></div><div className="actions"><button className="action" onClick={()=>location.href="/setup"}><span>＋</span>Set up business<b>›</b></button></div>{message&&<div className="notice">{message}</div>}</article></section><section className="grid lower"><article className="panel"><div className="panelHead"><div><span className="eyebrow">DATABASE</span><h2>Customers</h2></div></div><div className="empty"><div className="emptyIcon">♙</div><strong>{data.customers} customers</strong><p>Customer records are stored securely in Supabase.</p></div></article><article className="panel"><div className="panelHead"><div><span className="eyebrow">CASH FLOW</span><h2>Expenses</h2></div></div><div className="empty"><div className="emptyIcon">↘</div><strong>{money(data.expenses)} spent</strong><p>Expense totals are calculated from your database.</p></div></article></section><footer>Rapsometeddy Business OS · Supabase live data</footer></section></main>}