"use client";
import{useEffect,useState}from"react";
import{getSupabase}from"../../lib/supabase";

export default function Products(){
 const[s,setS]=useState(null),[b,setB]=useState(null),[rows,setRows]=useState([]),[name,setName]=useState(""),[description,setDescription]=useState(""),[price,setPrice]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const x=getSupabase();setS(x);if(!x)return;(async()=>{const{data:{user}}=await x.auth.getUser();if(!user){location.href="/setup";return}const{data:b}=await x.from("businesses").select("*").eq("owner_id",user.id).limit(1).maybeSingle();if(!b){location.href="/onboarding";return}setB(b);load(x,b.id)})()},[]);
 async function load(x,id){const{data,error}=await x.from("products").select("*").eq("business_id",id).eq("active",true).order("created_at",{ascending:false});if(!error)setRows(data||[]);else setMsg(error.message)}
 async function add(e){e.preventDefault();if(!s||!b)return;setBusy(true);setMsg("");const{error}=await s.from("products").insert({business_id:b.id,name:name.trim(),description:description.trim()||null,price:Number(price)});if(error)setMsg(error.message);else{setName("");setDescription("");setPrice("");setMsg("Product added.");load(s,b.id)}setBusy(false)}
 async function remove(id){if(!confirm("Remove this product?"))return;const{error}=await s.from("products").update({active:false}).eq("id",id).eq("business_id",b.id);if(error)setMsg(error.message);else load(s,b.id)}
 return <main className="simple"><header><button className="link" onClick={()=>location.href="/">← Dashboard</button><h1>Products</h1><p>Manage the products and services you sell.</p></header><section className="simpleGrid"><form className="panel form" onSubmit={add}><h2>Add product</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Product or service name" maxLength={120} required/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description (optional)" maxLength={250}/><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price (R)" required/><button className="primary" disabled={busy}>{busy?"Saving…":"Add product"}</button>{msg&&<div className="notice">{msg}</div>}</form><div className="panel"><h2>{rows.length} active products</h2>{rows.length===0?<div className="empty"><strong>No products yet</strong><p>Add your first product or service.</p></div>:rows.map(r=><div className="row" key={r.id}><div><strong>{r.name}</strong><span>{r.description||"Product or service"}</span></div><strong>R {Number(r.price).toFixed(2)}</strong><button className="link" onClick={()=>remove(r.id)}>Remove</button></div>)}</div></section></main>
}