"use client";
import{useEffect,useState}from"react";
import{getSupabase}from"../../lib/supabase";

export default function Sales(){
 const[s,setS]=useState(null),[b,setB]=useState(null),[rows,setRows]=useState([]),[products,setProducts]=useState([]),[customers,setCustomers]=useState([]),[productId,setProductId]=useState(""),[customerId,setCustomerId]=useState(""),[quantity,setQuantity]=useState("1"),[description,setDescription]=useState(""),[amount,setAmount]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const x=getSupabase();setS(x);if(!x)return;(async()=>{const{data:{user}}=await x.auth.getUser();if(!user){location.href="/setup";return}const{data:b}=await x.from("businesses").select("*").eq("owner_id",user.id).limit(1).maybeSingle();if(!b){location.href="/onboarding";return}setB(b);load(x,b.id)})()},[]);
 async function load(x,id){const[{data:sales},{data:prods},{data:cust}]=await Promise.all([x.from("sales").select("*,customers(name)").eq("business_id",id).order("sold_at",{ascending:false}),x.from("products").select("*").eq("business_id",id).eq("active",true).order("name"),x.from("customers").select("*").eq("business_id",id).order("name")]);setRows(sales||[]);setProducts(prods||[]);setCustomers(cust||[])}
 function chooseProduct(id){setProductId(id);const p=products.find(x=>x.id===id);if(p){setAmount((Number(p.price)*Math.max(1,Number(quantity)||1)).toFixed(2));if(!description)setDescription(p.name)}}
 function changeQty(v){const q=Math.max(1,Number(v)||1);setQuantity(String(q));const p=products.find(x=>x.id===productId);if(p)setAmount((Number(p.price)*q).toFixed(2))}
 async function add(e){e.preventDefault();if(!s||!b)return;setBusy(true);setMsg("");const finalAmount=Number(amount);if(!finalAmount||finalAmount<0){setMsg("Enter a valid amount.");setBusy(false);return}const p=products.find(x=>x.id===productId);const finalDescription=description.trim()||(p?p.name:"Sale");const{error}=await s.from("sales").insert({business_id:b.id,customer_id:customerId||null,description:finalDescription,amount:finalAmount});if(error)setMsg(error.message);else{setDescription("");setAmount("");setProductId("");setCustomerId("");setQuantity("1");setMsg("Sale recorded.");load(s,b.id)}setBusy(false)}
 return <main className="simple"><header><button className="link" onClick={()=>location.href="/">← Dashboard</button><h1>Sales</h1><p>Record sales using your products and customers.</p></header><section className="simpleGrid"><form className="panel form" onSubmit={add}><h2>Record sale</h2><select value={productId} onChange={e=>chooseProduct(e.target.value)}><option value="">Choose product or enter custom sale</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — R {Number(p.price).toFixed(2)}</option>)}</select><select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">No customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{productId&&<input type="number" min="1" step="1" value={quantity} onChange={e=>changeQty(e.target.value)} placeholder="Quantity"/>}<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description"/><input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount (R)" required/><button className="primary" disabled={busy}>{busy?"Saving…":"Save sale"}</button>{msg&&<div className="notice">{msg}</div>}</form><div className="panel"><h2>Recent sales</h2>{rows.length===0?<div className="empty"><strong>No sales yet</strong><p>Your recorded sales will appear here.</p></div>:rows.map(r=><div className="row" key={r.id}><div><strong>{r.description||"Sale"}</strong><span>{r.customers?.name||"No customer"} · {new Date(r.sold_at).toLocaleDateString("en-ZA")}</span></div><strong>R {Number(r.amount).toFixed(2)}</strong></div>)}</div></section></main>
}